/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 04-фев-2022 8:28:29 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Accounts_AccountsTypes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Accounts] DROP CONSTRAINT [FK_Accounts_AccountsTypes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Accounts_Contracts]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Accounts] DROP CONSTRAINT [FK_Accounts_Contracts]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Accounts_Currencies]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Accounts] DROP CONSTRAINT [FK_Accounts_Currencies]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Accounts_Users]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Accounts] DROP CONSTRAINT [FK_Accounts_Users]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Contracts_Currencies]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Contracts] DROP CONSTRAINT [FK_Contracts_Currencies]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Contracts_DepositTypes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Contracts] DROP CONSTRAINT [FK_Contracts_DepositTypes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Cities]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Cities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Countries]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Countries]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Disabilities]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Disabilities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_MaritalStatuses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_MaritalStatuses]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Accounts]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Accounts]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[AccountsTypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [AccountsTypes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Contracts]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Contracts]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Countries]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Countries]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Currencies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Currencies]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DepositTypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DepositTypes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Disabilities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Disabilities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MaritalStatuses]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MaritalStatuses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Users]
GO

/* Create Tables */

CREATE TABLE [Accounts]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Number] char(13) NOT NULL,
	[Code] varchar(50) NOT NULL,
	[Active] tinyint NOT NULL,
	[Debit] money NOT NULL,
	[Credit] money NOT NULL,
	[Balance] money NULL,
	[Owner] int NULL,
	[AccountType] tinyint NOT NULL,
	[Currency] tinyint NOT NULL,
	[Contract] int NULL
)
GO

CREATE TABLE [AccountsTypes]
(
	[Id] tinyint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL,
	[Code] char(4) NOT NULL
)
GO

CREATE TABLE [Cities]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Contracts]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[StartDate] date NOT NULL,
	[EndDate] date NOT NULL,
	[Sum] money NOT NULL,
	[Percent] float NOT NULL,
	[Currency] tinyint NOT NULL,
	[DepositType] smallint NULL
)
GO

CREATE TABLE [Countries]
(
	[Id] tinyint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Currencies]
(
	[Id] tinyint NOT NULL IDENTITY (1, 1),
	[Code] char(3) NOT NULL
)
GO

CREATE TABLE [DepositTypes]
(
	[Id] smallint NOT NULL IDENTITY (1, 1),
	[IsRevocable] bit NOT NULL,
	[Duration] int NOT NULL,
	[OfflinePercentByn] float NOT NULL,
	[OfflinePercentUsd] float NOT NULL,
	[OnlinePercentByn] float NOT NULL,
	[OnlinePercentUsd] float NOT NULL
)
GO

CREATE TABLE [Disabilities]
(
	[Id] smallint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [MaritalStatuses]
(
	[Id] tinyint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Users]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(50) NOT NULL,
	[Surname] nvarchar(50) NOT NULL,
	[Lastname] nvarchar(50) NOT NULL,
	[BirthDate] date NOT NULL,
	[Sex] bit NOT NULL,
	[PassportSeries] varchar(30) NOT NULL,
	[PassportNumber] varchar(30) NOT NULL,
	[IssuedBy] nvarchar(50) NOT NULL,
	[IssuedDate] date NOT NULL,
	[PassportId] varchar(50) NOT NULL,
	[BirthPlace] nvarchar(50) NOT NULL,
	[ResidenceCity] int NOT NULL,
	[ResidenceAddress] nvarchar(50) NOT NULL,
	[HomePhone] varchar(50) NULL,
	[MobilePhone] varchar(50) NULL,
	[Email] varchar(50) NULL,
	[MaritalStatus] tinyint NOT NULL,
	[Citizenship] tinyint NOT NULL,
	[Disability] smallint NOT NULL,
	[IsRetiree] bit NOT NULL,
	[MonthlyIncome] money NULL,
	[IsConscripted] bit NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Accounts] 
 ADD CONSTRAINT [PK_Accounts]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Accounts_AccountsTypes] 
 ON [Accounts] ([AccountType] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Accounts_Contracts] 
 ON [Accounts] ([Contract] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Accounts_Currencies] 
 ON [Accounts] ([Currency] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Accounts_Users] 
 ON [Accounts] ([Owner] ASC)
GO

ALTER TABLE [AccountsTypes] 
 ADD CONSTRAINT [PK_AccountsTypes]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Cities] 
 ADD CONSTRAINT [PK_Cities]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Contracts] 
 ADD CONSTRAINT [PK_Contracts]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Contracts_Currencies] 
 ON [Contracts] ([Currency] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Contracts_DepositTypes] 
 ON [Contracts] ([DepositType] ASC)
GO

ALTER TABLE [Countries] 
 ADD CONSTRAINT [PK_Countries]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Currencies] 
 ADD CONSTRAINT [PK_Currencies]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [DepositTypes] 
 ADD CONSTRAINT [PK_DepositTypes]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Disabilities] 
 ADD CONSTRAINT [PK_Disabilities]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [MaritalStatuses] 
 ADD CONSTRAINT [PK_MaritalStatuses]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Users] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Users] 
 ADD CONSTRAINT [UNQ_PassportId] UNIQUE NONCLUSTERED ([PassportId] ASC)
GO

ALTER TABLE [Users] 
 ADD CONSTRAINT [UNQ_PassportNumber] UNIQUE NONCLUSTERED ([PassportNumber] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Cities] 
 ON [Users] ([ResidenceCity] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Countries] 
 ON [Users] ([Citizenship] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Disabilities] 
 ON [Users] ([Disability] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_MaritalStatuses] 
 ON [Users] ([MaritalStatus] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Accounts] ADD CONSTRAINT [FK_Accounts_AccountsTypes]
	FOREIGN KEY ([AccountType]) REFERENCES [AccountsTypes] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Accounts] ADD CONSTRAINT [FK_Accounts_Contracts]
	FOREIGN KEY ([Contract]) REFERENCES [Contracts] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Accounts] ADD CONSTRAINT [FK_Accounts_Currencies]
	FOREIGN KEY ([Currency]) REFERENCES [Currencies] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Accounts] ADD CONSTRAINT [FK_Accounts_Users]
	FOREIGN KEY ([Owner]) REFERENCES [Users] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Contracts] ADD CONSTRAINT [FK_Contracts_Currencies]
	FOREIGN KEY ([Currency]) REFERENCES [Currencies] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Contracts] ADD CONSTRAINT [FK_Contracts_DepositTypes]
	FOREIGN KEY ([DepositType]) REFERENCES [DepositTypes] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Cities]
	FOREIGN KEY ([ResidenceCity]) REFERENCES [Cities] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Countries]
	FOREIGN KEY ([Citizenship]) REFERENCES [Countries] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Disabilities]
	FOREIGN KEY ([Disability]) REFERENCES [Disabilities] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_MaritalStatuses]
	FOREIGN KEY ([MaritalStatus]) REFERENCES [MaritalStatuses] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
