/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 27-янв-2022 20:43:39 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Cities]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Cities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Countries]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Countries]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Disabilities]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Disabilities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_MaritalStatuses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_MaritalStatuses]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Countries]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Countries]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Disabilities]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Disabilities]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MaritalStatuses]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MaritalStatuses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Users]
GO

/* Create Tables */

CREATE TABLE [Cities]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Countries]
(
	[Id] tinyint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Disabilities]
(
	[Id] smallint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NOT NULL
)
GO

CREATE TABLE [MaritalStatuses]
(
	[Id] tinyint NOT NULL IDENTITY (1, 1),
	[Name] varchar(50) NULL
)
GO

CREATE TABLE [Users]
(
	[Id] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(50) NOT NULL,
	[Surname] nvarchar(50) NOT NULL,
	[Lastname] nvarchar(50) NOT NULL,
	[BirthDate] date NOT NULL,
	[Sex] bit NOT NULL,
	[PassportSeries] varchar(30) NOT NULL,
	[PassportNumber] varchar(30) NOT NULL,
	[IssuedBy] nvarchar(50) NOT NULL,
	[IssuedDate] date NOT NULL,
	[PassportId] varchar(50) NOT NULL,
	[BirthPlace] nvarchar(50) NOT NULL,
	[ResidenceCity] int NOT NULL,
	[ResidenceAddress] nvarchar(50) NOT NULL,
	[HomePhone] varchar(50) NULL,
	[MobilePhone] varchar(50) NULL,
	[Email] varchar(50) NULL,
	[MaritalStatus] tinyint NOT NULL,
	[Citizenship] tinyint NOT NULL,
	[Disability] smallint NOT NULL,
	[IsRetiree] bit NOT NULL,
	[MonthlyIncome] money NULL,
	[IsConscripted] bit NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cities] 
 ADD CONSTRAINT [PK_Cities]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Countries] 
 ADD CONSTRAINT [PK_Countries]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Disabilities] 
 ADD CONSTRAINT [PK_Disabilities]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [MaritalStatuses] 
 ADD CONSTRAINT [PK_MaritalStatuses]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

ALTER TABLE [Users] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([Id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Cities] 
 ON [Users] ([ResidenceCity] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Countries] 
 ON [Users] ([Citizenship] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Disabilities] 
 ON [Users] ([Disability] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_MaritalStatuses] 
 ON [Users] ([MaritalStatus] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Cities]
	FOREIGN KEY ([ResidenceCity]) REFERENCES [Cities] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Countries]
	FOREIGN KEY ([Citizenship]) REFERENCES [Countries] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Disabilities]
	FOREIGN KEY ([Disability]) REFERENCES [Disabilities] ([Id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_MaritalStatuses]
	FOREIGN KEY ([MaritalStatus]) REFERENCES [MaritalStatuses] ([Id]) ON DELETE No Action ON UPDATE No Action
GO
